# Generated by Django 2.2.4 on 2020-02-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200209_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
